- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cells.kubeswift.io
  resources:
  - gpucellpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cells.kubeswift.io
  resources:
  - gpucellpools/finalizers
  verbs:
  - update
- apiGroups:
  - cells.kubeswift.io
  resources:
  - gpucellpools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - kubeswiftmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resource.k8s.io
  resources:
  - deviceclasses
  - resourceclaims
  - resourceclaimtemplates
  - resourceslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seed.kubeswift.io
  resources:
  - swiftseedprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - swift.kubeswift.io
  resources:
  - swiftguests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
