//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.StabilizationWindow != nil {
		in, out := &in.StabilizationWindow, &out.StabilizationWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSpec) DeepCopyInto(out *BootstrapSpec) {
	*out = *in
	if in.JoinSecretRef != nil {
		in, out := &in.JoinSecretRef, &out.JoinSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ReadyTimeout != nil {
		in, out := &in.ReadyTimeout, &out.ReadyTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSpec.
func (in *BootstrapSpec) DeepCopy() *BootstrapSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacitySpec) DeepCopyInto(out *CapacitySpec) {
	*out = *in
	if in.HAMi != nil {
		in, out := &in.HAMi, &out.HAMi
		*out = new(HAMiSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadyTimeout != nil {
		in, out := &in.ReadyTimeout, &out.ReadyTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacitySpec.
func (in *CapacitySpec) DeepCopy() *CapacitySpec {
	if in == nil {
		return nil
	}
	out := new(CapacitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellGPUDRASpec) DeepCopyInto(out *CellGPUDRASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellGPUDRASpec.
func (in *CellGPUDRASpec) DeepCopy() *CellGPUDRASpec {
	if in == nil {
		return nil
	}
	out := new(CellGPUDRASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellGPUNativeSpec) DeepCopyInto(out *CellGPUNativeSpec) {
	*out = *in
	out.GPUProfileRef = in.GPUProfileRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellGPUNativeSpec.
func (in *CellGPUNativeSpec) DeepCopy() *CellGPUNativeSpec {
	if in == nil {
		return nil
	}
	out := new(CellGPUNativeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellGPUSpec) DeepCopyInto(out *CellGPUSpec) {
	*out = *in
	if in.DRA != nil {
		in, out := &in.DRA, &out.DRA
		*out = new(CellGPUDRASpec)
		**out = **in
	}
	if in.Native != nil {
		in, out := &in.Native, &out.Native
		*out = new(CellGPUNativeSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellGPUSpec.
func (in *CellGPUSpec) DeepCopy() *CellGPUSpec {
	if in == nil {
		return nil
	}
	out := new(CellGPUSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellSpec) DeepCopyInto(out *CellSpec) {
	*out = *in
	in.GuestTemplate.DeepCopyInto(&out.GuestTemplate)
	in.GPU.DeepCopyInto(&out.GPU)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellSpec.
func (in *CellSpec) DeepCopy() *CellSpec {
	if in == nil {
		return nil
	}
	out := new(CellSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellStatus) DeepCopyInto(out *CellStatus) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellStatus.
func (in *CellStatus) DeepCopy() *CellStatus {
	if in == nil {
		return nil
	}
	out := new(CellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeCapacity) DeepCopyInto(out *ComputeCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeCapacity.
func (in *ComputeCapacity) DeepCopy() *ComputeCapacity {
	if in == nil {
		return nil
	}
	out := new(ComputeCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionSpec) DeepCopyInto(out *DeletionSpec) {
	*out = *in
	if in.DrainTimeout != nil {
		in, out := &in.DrainTimeout, &out.DrainTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionSpec.
func (in *DeletionSpec) DeepCopy() *DeletionSpec {
	if in == nil {
		return nil
	}
	out := new(DeletionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemandStatus) DeepCopyInto(out *DemandStatus) {
	*out = *in
	if in.LastObserved != nil {
		in, out := &in.LastObserved, &out.LastObserved
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemandStatus.
func (in *DemandStatus) DeepCopy() *DemandStatus {
	if in == nil {
		return nil
	}
	out := new(DemandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCellPool) DeepCopyInto(out *GPUCellPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCellPool.
func (in *GPUCellPool) DeepCopy() *GPUCellPool {
	if in == nil {
		return nil
	}
	out := new(GPUCellPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUCellPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCellPoolList) DeepCopyInto(out *GPUCellPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GPUCellPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCellPoolList.
func (in *GPUCellPoolList) DeepCopy() *GPUCellPoolList {
	if in == nil {
		return nil
	}
	out := new(GPUCellPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GPUCellPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCellPoolSpec) DeepCopyInto(out *GPUCellPoolSpec) {
	*out = *in
	in.Cell.DeepCopyInto(&out.Cell)
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
	in.WorkloadCluster.DeepCopyInto(&out.WorkloadCluster)
	in.Capacity.DeepCopyInto(&out.Capacity)
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Deletion != nil {
		in, out := &in.Deletion, &out.Deletion
		*out = new(DeletionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCellPoolSpec.
func (in *GPUCellPoolSpec) DeepCopy() *GPUCellPoolSpec {
	if in == nil {
		return nil
	}
	out := new(GPUCellPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUCellPoolStatus) DeepCopyInto(out *GPUCellPoolStatus) {
	*out = *in
	if in.Demand != nil {
		in, out := &in.Demand, &out.Demand
		*out = new(DemandStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastScaleUpTime != nil {
		in, out := &in.LastScaleUpTime, &out.LastScaleUpTime
		*out = (*in).DeepCopy()
	}
	if in.PhysicalCapacity != nil {
		in, out := &in.PhysicalCapacity, &out.PhysicalCapacity
		*out = new(PhysicalCapacityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadCapacity != nil {
		in, out := &in.WorkloadCapacity, &out.WorkloadCapacity
		*out = new(WorkloadCapacityStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]CellStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUCellPoolStatus.
func (in *GPUCellPoolStatus) DeepCopy() *GPUCellPoolStatus {
	if in == nil {
		return nil
	}
	out := new(GPUCellPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HAMiSpec) DeepCopyInto(out *HAMiSpec) {
	*out = *in
	if in.ExpectedDevicesPerCell != nil {
		in, out := &in.ExpectedDevicesPerCell, &out.ExpectedDevicesPerCell
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HAMiSpec.
func (in *HAMiSpec) DeepCopy() *HAMiSpec {
	if in == nil {
		return nil
	}
	out := new(HAMiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryCapacity) DeepCopyInto(out *MemoryCapacity) {
	*out = *in
	out.Total = in.Total.DeepCopy()
	out.Allocated = in.Allocated.DeepCopy()
	out.Available = in.Available.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryCapacity.
func (in *MemoryCapacity) DeepCopy() *MemoryCapacity {
	if in == nil {
		return nil
	}
	out := new(MemoryCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCapacity) DeepCopyInto(out *ModelCapacity) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.Compute != nil {
		in, out := &in.Compute, &out.Compute
		*out = new(ComputeCapacity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCapacity.
func (in *ModelCapacity) DeepCopy() *ModelCapacity {
	if in == nil {
		return nil
	}
	out := new(ModelCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PhysicalCapacityStatus) DeepCopyInto(out *PhysicalCapacityStatus) {
	*out = *in
	if in.FreeGPUsInCluster != nil {
		in, out := &in.FreeGPUsInCluster, &out.FreeGPUsInCluster
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PhysicalCapacityStatus.
func (in *PhysicalCapacityStatus) DeepCopy() *PhysicalCapacityStatus {
	if in == nil {
		return nil
	}
	out := new(PhysicalCapacityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadCapacityStatus) DeepCopyInto(out *WorkloadCapacityStatus) {
	*out = *in
	if in.GPUMemory != nil {
		in, out := &in.GPUMemory, &out.GPUMemory
		*out = new(MemoryCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.GPUCompute != nil {
		in, out := &in.GPUCompute, &out.GPUCompute
		*out = new(ComputeCapacity)
		**out = **in
	}
	if in.ByModel != nil {
		in, out := &in.ByModel, &out.ByModel
		*out = make([]ModelCapacity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastObserved != nil {
		in, out := &in.LastObserved, &out.LastObserved
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadCapacityStatus.
func (in *WorkloadCapacityStatus) DeepCopy() *WorkloadCapacityStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadCapacityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadClusterSpec) DeepCopyInto(out *WorkloadClusterSpec) {
	*out = *in
	out.KubeconfigSecretRef = in.KubeconfigSecretRef
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(WorkloadNodeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadClusterSpec.
func (in *WorkloadClusterSpec) DeepCopy() *WorkloadClusterSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadNodeSpec) DeepCopyInto(out *WorkloadNodeSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Taints != nil {
		in, out := &in.Taints, &out.Taints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadNodeSpec.
func (in *WorkloadNodeSpec) DeepCopy() *WorkloadNodeSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadNodeSpec)
	in.DeepCopyInto(out)
	return out
}
